In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np


In [14]:
list_arr = [1,2,3,4]

In [15]:
arr = np.array(list_arr)

In [16]:
arr

array([1, 2, 3, 4])

In [18]:
print(type(arr))

<class 'numpy.ndarray'>


In [21]:
print(arr.dtype)

int32


In [27]:
random_arr = np.random.randint(1,50,size=(10))

In [28]:
random_arr

array([25, 35, 23, 23, 31,  6, 22, 40,  3, 45])

תרגיל 2

In [25]:
random_array = np.random.randint(10,100,size=(2,5))

In [26]:
random_array

array([[60, 39, 82, 13, 77],
       [51, 84, 17, 46, 49]])

המשך תרגול

תרגיל 1

In [31]:
np.mean(random_arr)

25.3

In [32]:
arr1 = [1,2,3]
arr2 = [4,5,6]

In [35]:
arr3 = arr1+arr2

In [36]:
arr3

[1, 2, 3, 4, 5, 6]

In [37]:
np.mean(arr3)

3.5

תרגיל 3

In [38]:
arr4 = np.random.randint(1,100,size=(20))

In [39]:
filter_arr = arr4[arr4>50]

In [40]:
filter_arr

array([96, 64, 52, 73, 70, 52, 66, 97])

תרגיל 4

In [49]:
arr5 = np.arange(10)
np.random.shuffle(arr5)

In [51]:
arr5

array([1, 6, 0, 8, 5, 3, 2, 4, 9, 7])

In [53]:
np.random.choice(5, 9)

array([1, 2, 4, 3, 4, 0, 3, 0, 2])